apiVersion: apps/v1
kind:  Deployment
metadata:
  name: nginx-depl
  annotations:
  kubernetes.io/change-cause: "Initial deployment"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      name: nginx-pod-spec
      labels:
         app: nginx-pod
    spec:
      serviceAccountName: bsc-ssd-y4-2025-sa
      containers:
      - name: nginx
        image: nginx:1.24.0
        ports:
        - containerPort: 80
