apiVersion: apps/v1
kind:  Deployment
metadata:
  name: nginx-depl
  annotations:
  kubernetes.io/change-cause: "Initial deployment"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      name: nginx-pod-spec
      labels:
         app: nginx-pod
    spec:
      serviceAccountName: bsc-ssd-y4-2025-sa
      containers:
      - name: nginx
        image: nginx:1.24.0
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP     # Default
  selector:           # How to match a service to its pods.
    app: nginx-pod
  ports:
  - port: 8080       # Port that the service receives requests
    targetPort: 80   # The container's port

